# Generated by Django 4.2.5 on 2023-09-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='power',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='rarity',
            field=models.IntegerField(default=0),
        ),
    ]
